ls:
  # directories
  .dir: kebab-case  | regex:__tests__ | regex:__mocks__ | regex:__data__

  # shell scripts
  .sh: kebab-case

  # source files
  # this is essentially kebab-case.with-custom.extentions.js
  .js: regex:([a-z]+)([a-z0-9]*)([-.][a-z0-9]+)*
  .ts: regex:([a-z]+)([a-z0-9]*)([-.][a-z0-9]+)*

# ignored directories and files
ignore:
  - node_modules
  - .git
  - .github
  - .vscode
  - .husky
  - dist
  - .commitlintrc.js
  - .eslintrc.js
  - .prettierrc.js
