export enum CollectionEnum {
  EnumDeliveryStatus = 'enum_delivery_status',
  EnumDeliveryType = 'enum_delivery_type',
  EnumOfferType = 'enum_offer_type',
  EnumPaymentMethod = 'enum_payment_method',
  EnumProductTypes = 'enum_product_types',
  EnumUserRoles = 'enum_user_roles',
  OrderItems = 'order_items',
  Orders = 'orders',
  ProductCategories = 'product_categories',
  ProductReviews = 'product_reviews',
  Products = 'products',
  Stores = 'stores',
  Users = 'users',
}
