type filterType =
  | 'name'
  | 'productCode'
  | 'store'
  | 'offer'
  | 'isPromoted'
  | 'productCategories'
  | 'productTypes'
  | 'createdBy'
  | 'updatedBy'
  | 'price'
  | 'availableQuantity'
  | 'ratingAverage'
  | 'createdAt'
  | 'updatedAt';
