export enum ProductTypeEnum {
  Smartphones = 'Smartphones',
  Laptops = 'Laptops',
  TShirts = 'T-Shirts',
  Dresses = 'Dresses',
  Shoes = 'Shoes',
  Sneakers = 'Sneakers',
  Skincare = 'Skincare',
  Makeup = 'Makeup',
  Haircare = 'Haircare',
  Chairs = 'Chairs',
  Tables = 'Tables',
  Underwear = 'Underwear',
  Hats = 'Hats',
  Plants = 'Plants',
  Mirrors = 'Mirrors',
}
